language: python
sudo: required
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get -y install python python-dev python-pip libffi-dev libssl-dev libjpeg-dev libmysqlclient-dev memcached tmux mysql-client
  - pip install -r api/requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'create database openctf;'
script:
  - export SQLALCHEMY_DATABASE_URI=mysql://root:@localhost/openctf
  - coverage run --source api -m pytest -v && coverage report
services:
  - mysql
after_success:
  coveralls
notifications:
  email: false
