openctf:
  build: nginx
  links:
    - api
    - sandbox
  ports:
    - "80:80"
  volumes:
    - ./nginx/web:/srv/http/ctf

api:
  build: api
  env_file: .env
  links:
    - db
    - sandbox
  expose:
    - 8000
  volumes:
    - ./api:/openctf
  entrypoint: ./wait-for-it.sh db

db:
  build: mysql
  env_file: .env
  expose:
    - 3306

sandbox:
  build: sandbox
  volumes:
    - ./sandbox:/sandbox
  expose:
    - 4000