name: documentation

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        working-directory: ./docs
        with:
          mdbook-version: '0.3.7'

      - run: mdbook build
        working-directory: ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        working-directory: ./docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
